# Generated by Django 5.2.6 on 2025-10-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='contents',
            field=models.CharField(max_length=500),
        ),
    ]
